/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Jersey {
  'id' : string,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : Time,
  'team' : string,
  'description' : string,
  'sizes' : Array<string>,
  'imageId' : [] | [ExternalBlob],
  'priceCents' : bigint,
}
export interface NewOrder {
  'customerName' : string,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'jerseyId' : string,
  'jerseyName' : string,
  'size' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJersey' : ActorMethod<[Jersey], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJersey' : ActorMethod<[string], undefined>,
  'getAllJerseys' : ActorMethod<[], Array<Jersey>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedJerseys' : ActorMethod<[], Array<Jersey>>,
  'getJersey' : ActorMethod<[string], Jersey>,
  'getOrder' : ActorMethod<[string], Order>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitOrder' : ActorMethod<[NewOrder], string>,
  'toggleFeatured' : ActorMethod<[string], undefined>,
  'toggleInStock' : ActorMethod<[string], undefined>,
  'updateJersey' : ActorMethod<[Jersey], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];