/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Jersey = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'team' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageId' : IDL.Opt(ExternalBlob),
  'priceCents' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'jerseyId' : IDL.Text,
  'jerseyName' : IDL.Text,
  'size' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const NewOrder = IDL.Record({
  'customerName' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJersey' : IDL.Func([Jersey], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJersey' : IDL.Func([IDL.Text], [], []),
  'getAllJerseys' : IDL.Func([], [IDL.Vec(Jersey)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedJerseys' : IDL.Func([], [IDL.Vec(Jersey)], ['query']),
  'getJersey' : IDL.Func([IDL.Text], [Jersey], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitOrder' : IDL.Func([NewOrder], [IDL.Text], []),
  'toggleFeatured' : IDL.Func([IDL.Text], [], []),
  'toggleInStock' : IDL.Func([IDL.Text], [], []),
  'updateJersey' : IDL.Func([Jersey], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Jersey = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'team' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageId' : IDL.Opt(ExternalBlob),
    'priceCents' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'jerseyId' : IDL.Text,
    'jerseyName' : IDL.Text,
    'size' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const NewOrder = IDL.Record({
    'customerName' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJersey' : IDL.Func([Jersey], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJersey' : IDL.Func([IDL.Text], [], []),
    'getAllJerseys' : IDL.Func([], [IDL.Vec(Jersey)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedJerseys' : IDL.Func([], [IDL.Vec(Jersey)], ['query']),
    'getJersey' : IDL.Func([IDL.Text], [Jersey], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitOrder' : IDL.Func([NewOrder], [IDL.Text], []),
    'toggleFeatured' : IDL.Func([IDL.Text], [], []),
    'toggleInStock' : IDL.Func([IDL.Text], [], []),
    'updateJersey' : IDL.Func([Jersey], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };